### ISSUE TITLE
error when running "configure" script

### ISSUE THREAD

**Issue by ahiliation** [GNUFreetalk/freetalk#26]
x----screenshot showing error ----x

$./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether make sets $(MAKE)... (cached) yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking argp.h usability... yes
checking argp.h presence... yes
checking for argp.h... yes
checking for readline in -lreadline -lcurses... yes
checking for readline in -lreadline -ltermcap... yes
checking for readline in -lreadline -lncurses... yes
checking for library containing tgetent... -lncurses
checking for readline in -lreadline... yes
checking for pkg-config... yes
./configure: line 4961: syntax error near unexpected token `GUILE,'
./configure: line 4961: `PKG_CHECK_MODULES(GUILE, guile-2.0, HAVE_GUILE_2="yes", HAVE_GUILE_2="no")'
$

**Comment by harshavardhana** [comment]
> ./configure: line 4961: syntax error near unexpected token GUILE,' ./configure: line 4961:PKG_CHECK_MODULES(GUILE, guile-2.0, HAVE_GUILE_2="yes", HAVE_GUILE_2="no")'
> $

Is `pkg-config` installed?  once its installed you have to run 

~~~
# ./autogen.sh
# ./configure
~~~

**Comment by ahiliation** [comment]
I  had not executed  autogen.sh after i installed pkg-config.
i did run autogen.sh now and i got that error cleared.
Thanks a lot :)

**Comment by ahiliation** [comment]
I  had not executed  autogen.sh after i installed pkg-config.i did run autogen.sh now and i got that error cleared.Thanks a lot :)




software engineerRajagiri school of engineering and technology

**Comment by harshavardhana** [comment]
No problem!
