### ISSUE TITLE
Cannot install freetalk on Cygwin because sudo command not found

### ISSUE THREAD

**Issue by longk15t** [GNUFreetalk/freetalk#28]
Hi @harshavardhana 
In this page https://gnufreetalk.github.io/ it said type sudo make install to install freetalk but I'm using cygwin, and sudo command is not found.

Any solution to be able install freetalk without sudo ?

**Comment by harshavardhana** [comment]
> Any solution to be able install freetalk without sudo ?

We never really tested Freetalk on cygwin so given there will be issues, but you don't need sudo to install Freetalk. 

On cygwin you can easily specify a custom destination directory.

~~~
$ ./configure
$ make install DESTDIR=freetalk

$ export PATH=$PATH:${HOME}/freetalk/usr/bin
$ freetalk
....
~~~

**Comment by longk15t** [comment]
Cannot execute 2nd command: $ make install DESTDIR=freetalk
It said: 
make: *** No rule to make target 'install'. Stop.

**Comment by harshavardhana** [comment]
> Cannot execute 2nd command: $ make install DESTDIR=freetalk

did you do the below command? 

> ./configure --prefix=/usr

**Comment by longk15t** [comment]
I did, still same error
My commands as below
cd freetalk.git/
./configure
./configure --prefix=/usr
make install DESTDIR=freetalk

It returns same above error: 
make: *** No rule to make target 'install'. Stop.

**Comment by harshavardhana** [comment]
You don't have a C++ compiler installed, ./configure failed.  Install c++ compiler it will work.

**Comment by longk15t** [comment]
Thanks, but this is what happen next.
![error](https://cloud.githubusercontent.com/assets/6722910/9247998/4ff93d14-41e2-11e5-8a9e-413254f1a679.png)

It said : readline not found..

**Comment by harshavardhana** [comment]
> It said : readline not found..

Yes even on cygwin windows, one needs to install all the dependencies

- libloudmouth
- libreadline
- libguile > 2.0
- libglib

IT can get a little harder here, since some of these packages are not available on cygwin. Can you try out in a Linux virtual machine? using perhaps vagrant?

https://www.vagrantup.com/downloads.html

http://docs.vagrantup.com/v2/getting-started/index.html

**Comment by longk15t** [comment]
thanks,
so, any plan to support freetalk on Windows ?

BTW, you can close this issue.

**Comment by harshavardhana** [comment]
> so, any plan to support freetalk on Windows ?

No it won't be there is no way to get it working
