### ISSUE TITLE
configure error

### ISSUE THREAD

**Issue by darthlukan** [GNUFreetalk/freetalk#30]
When running the configure step against the 4.1 branch, I get the following error:

```
    config.status: error: cannot find input file: 'src/Makefile.in'
```

**Comment by Wildefyr** [comment]
Hey darth, you need to run ./autogen.sh for it generate that file. configure will then check you have the needed dependencies.

- wild

**Comment by darthlukan** [comment]
@Wildefyr I did run ./autogen.sh, it then said it was okay to configure.

**Comment by vadmeste** [comment]
@darthlukan, could you post the complete output of ./autogen.sh ?

**Comment by darthlukan** [comment]
Sure thing:

```
... Freetalk autogen ...

Running aclocal...
Running autoheader...
Running autoconf...
Running automake...
configure.ac:41: installing './compile'
configure.ac:7: installing './install-sh'
configure.ac:7: installing './missing'
doc/Makefile.am:3: installing 'doc/mdate-sh'
doc/Makefile.am:3: error: required file 'doc/texinfo.tex' not found
src/Makefile.am: installing './depcomp'
Running autogen.sh in argp-standalone ...
configure.ac:19: installing './compile'
configure.ac:10: installing './install-sh'
configure.ac:10: installing './missing'
Makefile.am: installing './depcomp'

Please proceed with configuring, compiling, and installing.
```

**Comment by harshavardhana** [comment]
> doc/Makefile.am:3: error: required file 'doc/texinfo.tex' not found

Do you have GNU texinfo installed?

**Comment by darthlukan** [comment]
@harshavardhana - No, I don't. I didn't see it listed as a dependency. I'll install it now and report back.

**Comment by darthlukan** [comment]
@harshavardhana - I have texinfo installed and I still get the same output. I notice there's no texinfo.tex file in the doc dir of the unpacked sources. Is autogen.sh supposed to generate that as well?

**Comment by harshavardhana** [comment]
> @harshavardhana - I have texinfo installed and I still get the same output. I notice there's no texinfo.tex file in the doc dir of the unpacked sources. Is autogen.sh supposed to generate that as well?

yes it is supposed to generate that - it is part of automake tools. Not sure why this would happen.

**Comment by harshavardhana** [comment]
For example this should be the message 

```
$ ./autogen.sh

... Freetalk autogen ...

Running aclocal...
Running autoheader...
Running autoconf...
Running automake...
doc/Makefile.am:3: installing 'doc/mdate-sh'
doc/Makefile.am:3: installing 'doc/texinfo.tex'
....
```

**Comment by harshavardhana** [comment]
Can you paste you "autoconf, automake, aclocal" versions?

**Comment by darthlukan** [comment]
Automake: 1.15
Autoconf: 2.69
Aclocal: 1.15

Just in case, the version of texinfo that I installed was 6.0.

**Comment by darthlukan** [comment]
I checked the config.log file in my working directory and saw a few errors that might bring us closer to figuring this one out. Here's the gist: https://gist.github.com/anonymous/23bd5550e7cd558dd6d1

**Comment by vadmeste** [comment]
The config error ```config.status:869: error: cannot find input file: `src/Makefile.in'``` is related to ```error: required file 'doc/texinfo.tex' not found```... I can easily reproduce this error when I delete doc/freetalk.texi then ./autogen.sh then ./configure... However, in the normal state, I don't have the error though I have the same version of automake/autoconf/aclocal mentioned by @darthlukan

**Comment by darthlukan** [comment]
@vadmeste - Yeah, it's really strange. freetalk.texi is in there, yet I get the error. I'm not sure how to go about fixing it though, else I'd have definitely sent a PR by now.

**Comment by harshavardhana** [comment]
here is what you can try.. 

```
$ make gitclean
```

```
$ ./autogen.sh
``` 

Again and see if you see the same problem.

**Comment by darthlukan** [comment]
@harshavardhana - Here's the error I get with that.

```
make gitclean
make: *** No rule to make target 'gitclean'.  Stop.
```

**Comment by darthlukan** [comment]
@harshavardhana - I'm assuming it was you that suggested the following. I've tried it by performing a git clone and checking out the 4.1 branch and I've also tried it with the v4.1.zip, the results are the same.

Your suggestion:

"""Ah i should have guessed "./configure" itself never succeeded - so yes you don't have a Makefile yet.  Lets try on a fresh extract of the tarball ?  - https://github.com/GNUFreetalk/freetalk/archive/v4.1.tar.gz"""

**Comment by vadmeste** [comment]
@darthlukan could you run ./autogen.sh then post the output of this command "automake -W=all -v --add-missing --copy --foreign", maybe we will find some useful information

**Comment by darthlukan** [comment]
@vadmeste - Here's the output:

```
⊡ ❱ automake -Wall -v --add-missing --copy --foreign 
automake: thread 0: reading autoconf --trace=AC_CONFIG_LIBOBJ_DIR:\$f:\$l::\$d::\$n::\${::}% --trace=AM_PROG_MKDIR_P:\$f:\$l::\$d::\$n::\${::}% --trace=AC_FC_SRCEXT:\$f:\$l::\$d::\$n::\${::}% --trace=_LT_AC_TAGCONFIG:\$f:\$l::\$d::\$n::\${::}% --trace=AC_LIBSOURCE:\$f:\$l::\$d::\$n::\${::}% --trace=AM_PROG_AR:\$f:\$l::\$d::\$n::\${::}% --trace=AC_SUBST_TRACE:\$f:\$l::\$d::\$n::\${::}% --trace=AC_CONFIG_AUX_DIR:\$f:\$l::\$d::\$n::\${::}% --trace=AC_CANONICAL_HOST:\$f:\$l::\$d::\$n::\${::}% --trace=AM_MAINTAINER_MODE:\$f:\$l::\$d::\$n::\${::}% --trace=AM_AUTOMAKE_VERSION:\$f:\$l::\$d::\$n::\${::}% --trace=_AM_COND_IF:\$f:\$l::\$d::\$n::\${::}% --trace=AC_CANONICAL_BUILD:\$f:\$l::\$d::\$n::\${::}% --trace=AM_CONDITIONAL:\$f:\$l::\$d::\$n::\${::}% --trace=AM_EXTRA_RECURSIVE_TARGETS:\$f:\$l::\$d::\$n::\${::}% --trace=_AM_COND_ELSE:\$f:\$l::\$d::\$n::\${::}% --trace=AC_CONFIG_FILES:\$f:\$l::\$d::\$n::\${::}% --trace=AC_REQUIRE_AUX_FILE:\$f:\$l::\$d::\$n::\${::}% --trace=_AM_COND_ENDIF:\$f:\$l::\$d::\$n::\${::}% --trace=m4_include:\$f:\$l::\$d::\$n::\${::}% --trace=AC_CONFIG_HEADERS:\$f:\$l::\$d::\$n::\${::}% --trace=AC_CONFIG_LINKS:\$f:\$l::\$d::\$n::\${::}% --trace=AM_GNU_GETTEXT:\$f:\$l::\$d::\$n::\${::}% --trace=_AM_SUBST_NOTMAKE:\$f:\$l::\$d::\$n::\${::}% --trace=m4_sinclude:\$f:\$l::\$d::\$n::\${::}% --trace=AC_CANONICAL_TARGET:\$f:\$l::\$d::\$n::\${::}% --trace=AM_GNU_GETTEXT_INTL_SUBDIR:\$f:\$l::\$d::\$n::\${::}% --trace=LT_SUPPORTED_TAG:\$f:\$l::\$d::\$n::\${::}% --trace=AM_INIT_AUTOMAKE:\$f:\$l::\$d::\$n::\${::}% --trace=AC_INIT:\$f:\$l::\$d::\$n::\${::}% --trace=sinclude:\$f:\$l::\$d::\$n::\${::}%
automake: thread 0: reading /usr/share/automake-1.15/am/header-vars.am
automake: thread 0: reading Makefile.am
automake: thread 0: reading /usr/share/automake-1.15/am/configure.am
automake: thread 0: reading /usr/share/automake-1.15/am/remake-hdr.am
automake: thread 0: reading /usr/share/automake-1.15/am/clean-hdr.am
automake: thread 0: reading /usr/share/automake-1.15/am/texinfos.am
automake: thread 0: reading /usr/share/automake-1.15/am/subdirs.am
automake: thread 0: reading /usr/share/automake-1.15/am/tags.am
automake: thread 0: reading /usr/share/automake-1.15/am/distdir.am
automake: thread 0: reading /usr/share/automake-1.15/am/footer.am
automake: thread 0: reading /usr/share/automake-1.15/am/install.am
automake: thread 0: reading /usr/share/automake-1.15/am/clean.am
automake: thread 0: creating Makefile.in
automake: thread 0: reading doc/Makefile.am
automake: thread 0: reading doc/freetalk.texi
automake: thread 0: reading /usr/share/automake-1.15/am/texibuild.am
automake: thread 0: reading /usr/share/automake-1.15/am/texi-vers.am
doc/Makefile.am:3: error: required file 'doc/texinfo.tex' not found
automake: thread 0: Sources ending in .dvi become .ps
automake: thread 0: reading /usr/share/automake-1.15/am/inst-vars.am
automake: thread 0: reading /usr/share/automake-1.15/am/mans.am
automake: thread 0: reading /usr/share/automake-1.15/am/mans-vars.am
automake: thread 0: not writing doc/Makefile.in because of earlier errors
automake: thread 0: reading examples/Makefile.am
automake: thread 0: reading /usr/share/automake-1.15/am/data.am
automake: thread 0: not writing examples/Makefile.in because of earlier errors
automake: thread 0: reading extensions/Makefile.am
automake: thread 0: not writing extensions/Makefile.in because of earlier errors
automake: thread 0: reading src/Makefile.am
automake: thread 0: reading /usr/share/automake-1.15/am/progs.am
automake: thread 0: reading /usr/share/automake-1.15/am/program.am
automake: thread 0: reading /usr/share/automake-1.15/am/compile.am
automake: thread 0: reading /usr/share/automake-1.15/am/depend.am
automake: thread 0: reading /usr/share/automake-1.15/am/depend2.am
automake: thread 0: Sources ending in .c become .o
automake: thread 0: Sources ending in .c become .obj
automake: thread 0: reading /usr/share/automake-1.15/am/lang-compile.am
automake: thread 0: reading /usr/share/automake-1.15/am/header.am
automake: thread 0: not writing src/Makefile.in because of earlier errors
```

**Comment by vadmeste** [comment]
Not much informative, could you post this ```strace -ff automake --add-missing --copy --foreign 2>&1``` ?

**Comment by darthlukan** [comment]
@vadmeste - Wow, that's a lot of output! Here's the gist: https://gist.githubusercontent.com/anonymous/fc7f99e14358db6ca0d8/raw/34ada8ee35ca047d55e923639d20fc81b7e6251b/stdin.txt

**Comment by vadmeste** [comment]
I can see this in your log:
```stat("/usr/share/automake-1.15/texinfo.tex", 0x2266280) = -1 ENOENT (No such file or directory)```

How did you install automake? Are you running an usual distribution ?

**Comment by darthlukan** [comment]
I'm running CRUX Linux. The version of automake that I have was part of the base distribution, so I didn't actually have to manually install it.

I'm looking at the Pkgfile for the port and it looks like the maintainer explicitly removed texinfo.tex:

```
rm $PKG/usr/share/automake-*/texinfo.tex
```

I'll check with the package maintainer to see what the reasoning behind that move was, but I think it's safe to say that we've found the source of the problem and it's a distro-specific issue, not a freetalk issue, so I'll mark this as resolved, "User didn't have an expected texinfo.tex file in their automake package distribution."

**Comment by harshavardhana** [comment]
@darthlukan - before you bother the package maintainer :-) - try a proper distribution - https://github.com/GNUFreetalk/freetalk/releases/download/v4.1/freetalk-4.1.tar.gz
