### ISSUE TITLE
freetalk, loudmouth problem

### ISSUE THREAD

**Issue by pito2901** [GNUFreetalk/freetalk#32]
Hi everyone !

When I run the following command : ./configure --prefix=/usr

I got the log until :
```
...
checking for LOUDMOUTH
configure: error: ERROR! loudmouth-1.0 not found...
```

So I try to install loudmouth, but I just got the perl library of loudmouth, I can't find the loudmouth-1.0 version.

Someone can help ?

Thanks.

**Comment by pito2901** [comment]
Got it !

You have to install the package `libloudmouth1-dev`

**Comment by vadmeste** [comment]
:+1:
