### ISSUE TITLE
Script freetalk

### ISSUE THREAD

**Issue by pito2901** [GNUFreetalk/freetalk#33]
Hi everyone !

I just want to know how to write and run script with freetalk, someone can help ?

Thanks.

**Comment by vadmeste** [comment]
@pito2901, could you elaborate what you need exactly?

By the way, Freetalk has some extension scripts which could help you:  https://github.com/GNUFreetalk/freetalk/tree/master/extensions

**Comment by pito2901** [comment]
Actually, I need to send login with jid and pass, send a message to some clients and logout...

Next, I need to get a list of all the clients who are connected to the server (ex: in a log).

**Comment by vadmeste** [comment]
@pito2901, the clean way is to use an XMPP library which is so simple especially with Python, otherwise you will have to write an extension for freetalk but I think it will get harder when your need grows

**Comment by pito2901** [comment]
Can you suggest me some xmpp libraries to do this ?
